"""initial

Revision ID: a2a69a01b658
Revises: 
Create Date: 2026-06-26 20:05:54.175834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a69a01b658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('product_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('uq_payment_reference', ['reference'])

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_reference', type_='unique')
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('product_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
